{
    'name': 'Odex Benefit Managment',
    'category': 'Grant Managment',
    'summary': '<Grant Benefit Management for takaful Project >',
    'version': '1.0',
    'sequence': 4,
    'website': 'http://exp-sa.com',
    'license': 'GPL-3',
    'author': 'Expert Ltd',
    'depends': ['base', 'takaful_core', 'website', 'account', 'report_xlsx', 'sale', 'product', 'stock', 'hr',
                'purchase','web_google_maps'],

    'data': [
        'security/security_view.xml',
        'security/ir.model.access.csv',

        'data/scheduled_actions.xml',
        'data/server_actions.xml',
        'data/email_temps.xml',
        'views/service_delivery_method.xml',
        'views/service_need_status.xml',
        'views/service_provider.xml',
        'views/benefit_config_view.xml',
        'views/actions_and_menus.xml',
        'views/benefit_view.xml',
        'views/users_inherit.xml',
        'views/branch_details.xml',
        'views/committees_view.xml',
        'views/detainee_family_research_view.xml',
        'views/branch_inherit.xml',
        'views/family_members.xml',
        'views/family_complaints.xml',
        'views/service_request_line.xml',
        'wizards/researcher_wizard.xml',
        'wizards/suspend_reason_wizard.xml',
        'wizards/exception_wizard.xml',
        'wizards/exchange_order_wizard.xml',
        'views/visit.xml',

        'views/main_service.xml',
        'views/member_location.xml',
        'views/family_validation_setting.xml',
        'views/ir_attachment_inherit.xml',
        'views/changes_requests.xml',
        'views/education_settings.xml',
        'views/health_genetic_diseases.xml',
        'views/payment_order.xml',
        # 'views/res_config_settings_view.xml',
        # 'views/benefit_expenses_view.xml',
        'views/sms_view.xml',
        'reports/benefit_template.xml',
        'views/benefit_services_view.xml',
        'views/family_expense_view.xml',
        'views/services_settings.xml',
        'views/service_request.xml',
        
        'views/generate_reports.xml',

        'views/res_country.xml',
        'templates/benefit_email.xml',
        'data/sequence_data.xml',
        'wizards/entity_refused_wizard_view.xml',
        'wizards/entity_black_list_wizard_view.xml',
    ],
    'external_dependencies': {
        'python': ['num2words'],
    },
}
