from . import ir_attachment_inherit
from . import benefit
from . import benefit_need
from . import benefit_config
from . import housing_config
from . import generate_reports
from . import Services
from . import sms
# from . import branch_inherit
from . import visit
from . import main_service
from . import member_location
from . import family_members
from . import member_diseases
from . import members_hobbies
from . import member_disabilities
from . import family_debits
from . import family_validation_setting
from . import expenses_type
from . import changes_requests
from . import education_settings
from . import hr_department
from . import account_move_line
from . import family_expense
from . import services_settings
from . import res_country_inherit
from . import service_request
from . import payment_order
from . import family_complaints
from . import health_genetic_diseases
from . import health_mental_illnesses
from . import health_chronic_diseases
# from . import res_config_settings