name: Pull Code

on:
  # push:
  #   branches:
  #     - preprod
  #     - test
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Server'
        required: true
        type: choice
        options:
          - client-stage
          - client-production
        default: client-stage

jobs:

  deploy_client_stage_server:
    name: Deploy Master Branch to Client Stage Server 
    runs-on: client_stage_server_trahum_project
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'client-stage'
    steps:
      - name: Checkout And Restart Project
        continue-on-error: false
        run: |
          echo "** [INFO] Running on branch -->  ${{ github.ref }}"
      
          # Run the main script
          echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -S chmod +x /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-master-pull_code.sh
          echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -E -S /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-master-pull_code.sh "${{ secrets.GH_TOKEN }}"
          
  deploy_client_prod_server:
    name: Deploy Master Branch to Client Prod Server 
    runs-on: client_prod_server_trahum_project
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'client-production'
    steps:
      - name: Checkout And Restart Project
        continue-on-error: false
        run: |
          echo "** [INFO] Running on branch -->  ${{ github.ref }}"
      
          # Run the main script
          echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -S chmod +x /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-master-pull_code.sh
          echo "${{ secrets.RUNNER_PASSWORD }}" | sudo -E -S /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-master-pull_code.sh "${{ secrets.GH_TOKEN }}"


  # deploy_preprod_on_app_server:
  #   name: Deploy to Preprod on App Server
  #   runs-on: trahum-app-server-runner
  #   if: github.ref == 'refs/heads/preprod' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'preprod')
  #   steps:
  #     - name: Checkout And Restart Project
  #       continue-on-error: false
  #       run: |
  #         sudo chmod +x /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-preprod-server.sh
  #         sudo /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-preprod-server.sh


  # deploy_test_on_app_server:
  #   name: Deploy to Test on App Server
  #   runs-on: trahum-app-server-runner
  #   if: github.ref == 'refs/heads/test' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
  #   steps:
  #     - name: Checkout And Restart Project
  #       continue-on-error: false
  #       run: |
  #         sudo chmod +x /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-dev-server.sh
  #         sudo /home/${{ secrets.CLIENT_USER }}/scripts/pull/trahum-dev-server.sh
